baseURL = "/"
locale = "en"
title = "Sarthak Mishra"
disableKinds = ["taxonomy", "term", "sitemap"]
enableRobotsTXT = true

[build]
  writeStats = false

[markup.goldmark.renderer]
  unsafe = false

[minify]
  minifyOutput = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
